### ISSUE TITLE
Bioconductor Formatting

### ISSUE THREAD

**Issue by jmitchell81** [FertigLab/dominoSignal#32]
# 06.18.24 Reviewer Comments 
 - [x] #126
 - [ ] 2. You still have at least one occurence of domino2 in your doc. Please make sure to find and correct them all.
 - [x] #124
 - [ ] 4. Four mysterious lines of code right below the title of the vignette and before any text. That's quite an unusual and pretty dry way to start a vignette! What is this code? What does it do? Why is it here? Does it work properly without explicitly loading any package first? What package(s)? 
 - [x] #125
 - [x] #123

# BiocCheck Errors
- [x] #35
- [x] #37
- [x] ERROR: Package directory 'domino' must match Package: field (got 'domino2').
- [x] #58
- [x] ERROR: Maintainer must add package name to Watched Tags on the support site; Edit your Support Site User Profile to add Watched Tags.
- [x] #56
- [x] #70
- [ ] pick new tiny examples to use with`testdata.R`
- [x] #110

# BiocCheck Warnings
- [x] #44
- [x] #38
- [x] #42

# BiocCheck Notes
- [x] #40
- [x] #39
- [x] NOTE: Update R version dependency from 3.6.2 to 4.2.0.
- [x] #45
- [x] NOTE:  'sessionInfo' not found in vignette(s)
- [ ] NOTE:  Avoid sapply(); use vapply()
- [ ] NOTE:  Avoid 1:...; use seq_len() or seq_along()
- [x] NOTE:  Avoid 'cat' and 'print' outside of 'show' methods
- [ ] NOTE:  Avoid the use of 'paste' in condition signals
- [x] #54
- [ ] NOTE: Consider shorter lines; 601 lines (15%) are > 80 characters long
- [x] #41
- [ ] NOTE: Consider multiples of 4 spaces for line indents; 1173 lines (29%) are not.
- [x] NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin credentials). Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

# shortening functions
### frequently used internal functions
- [x] gene ortholog conversion

### create_rl_map_cellphonedb
- [x] class checks for inputs
- [x] internal function for replacing empty cells with "False"
- [x] internal function Python -> R true/false syntax
- [x] construction of rl_map without for loop
- [ ] set fixed columns for receptor and ligand descriptions
- [ ]

**Comment by jmitchell81** [comment]
[00BiocCheck.log](https://github.com/FertigLab/domino_development/files/13032966/00BiocCheck.log)

BiocCheck() log from commit 0d16a1c as of 10/18/23

**Comment by kjkrishnan** [comment]
#125 Pretty sure this is because for some reason show and print were tagged as internal instead of exported. I think I fixed it on the krishnan_rmd_fix_134 branch, but we should double check to be sure

**Comment by dimalvovs** [comment]
all done!
